apiVersion: v1
kind: Service
metadata:
  name: feed-microservice
  labels:
    service: feed-microservice
    run: feed-microservice
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    service: feed-microservice
    run: feed-microservice